In [1]:
import torch

# Automatic differentiation using Pytorch

## Dynamic Comp Graph (DCG)

In [7]:
x = torch.tensor(2.0,requires_grad = True) # pytorch gradient tracking is enabled

In [8]:
# Define a function
y =  2*x**4 + x**3 + 3*x**2 + 5*x + 1

In [10]:
y # this is nothing but y when x = 2.0

tensor(63., grad_fn=<AddBackward0>)

# BackPropagation

In [11]:
y.backward()

In [14]:
x.grad # 1st order diff of the y wrt x

tensor(93.)

In [15]:
import numpy as np

In [16]:
arr = np.array([[1,2,3],[3,2,1]], dtype = np.float64)
arr

array([[1., 2., 3.],
       [3., 2., 1.]])

In [19]:
x = torch.tensor(arr, requires_grad= True)
x

tensor([[1., 2., 3.],
        [3., 2., 1.]], dtype=torch.float64, requires_grad=True)

In [20]:
y = 3*x + 2

In [21]:
y 

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], dtype=torch.float64, grad_fn=<AddBackward0>)

In [22]:
z = 2*y**2

In [23]:
z

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], dtype=torch.float64, grad_fn=<MulBackward0>)

In [24]:
out = z.mean()
out

tensor(140., dtype=torch.float64, grad_fn=<MeanBackward0>)

In [25]:
out.backward()

In [28]:
x.grad # this happens due to chain rule of differentiation

tensor([[10., 16., 22.],
        [22., 16., 10.]], dtype=torch.float64)