In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'1.7.0+cu110'

In [4]:
arr = np.array([1,2,3,4], dtype = np.int32)

In [5]:
arr

array([1, 2, 3, 4])

# Converting a numpy array into tensor

In [6]:
x = torch.from_numpy(arr)
x

tensor([1, 2, 3, 4], dtype=torch.int32)

In [7]:
type(x)

torch.Tensor

In [8]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [9]:
x.dtype

torch.int32

In [10]:
arr = np.arange(0.0, 12.0)

In [13]:
arr = arr.reshape((4,3))

In [14]:
arr

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [15]:
arr = torch.from_numpy(arr)
arr

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

# when using x = torch.from_numpy(arr) we create a link between arr and variable x so any changes in the original values will lead to change in tensor created

In [21]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [22]:
x = torch.from_numpy(a)
x

tensor([1, 2, 3, 4], dtype=torch.int32)

In [23]:
a[0] = 999
a

array([999,   2,   3,   4])

In [24]:
x

tensor([999,   2,   3,   4], dtype=torch.int32)

# In order to prevent this we can use torch.tensor(arr) in order to create a deep copy of arr

In [25]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [26]:
x = torch.tensor(a)
x

tensor([1, 2, 3, 4], dtype=torch.int32)

In [27]:
a[0] = 999
a

array([999,   2,   3,   4])

In [28]:
x

tensor([1, 2, 3, 4], dtype=torch.int32)

In [29]:
y = torch.Tensor(a) # .Tensor(arr) is an alias for .FloatTensor(arr) while .tensor() retains the original tensor dtype
y

tensor([999.,   2.,   3.,   4.])

# How to create tensor in PyTorch

In [32]:
torch.empty(2,2) # create a block of mem

tensor([[0.0000e+00, 2.1733e+00],
        [0.0000e+00, 6.1989e-06]])

In [33]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [34]:
torch.zeros(4,3, dtype = torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [36]:
torch.ones(4,3, dtype = torch.int32)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [38]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [41]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

# Converting a list to tensor

In [42]:
torch.tensor([1,2,4])

tensor([1, 2, 4])

In [43]:
torch.tensor([1,2,4]).type(torch.float64)

tensor([1., 2., 4.], dtype=torch.float64)

In [45]:
torch.randint(0,10,size = (3,3))

tensor([[6, 4, 5],
        [8, 5, 6],
        [1, 5, 2]])

In [46]:
torch.rand((2,3))

tensor([[0.7278, 0.4867, 0.3619],
        [0.7352, 0.4290, 0.1952]])

In [47]:
torch.randn((2,3))

tensor([[ 0.4728,  1.5660,  1.8735],
        [-0.1578, -0.1894, -0.5838]])

# Shape inheritence

In [55]:
a = torch.arange(1,13,1).reshape(4,3).type(torch.float32)
a

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [56]:
x = torch.rand_like(a) # rand_like or randn_like will inherit the shape of the input tensor
x

tensor([[0.7770, 0.8957, 0.1716],
        [0.0562, 0.4037, 0.4541],
        [0.3004, 0.3693, 0.6706],
        [0.1872, 0.0318, 0.0533]])

In [57]:
torch.randint_like(a , low = 0, high = 10)

tensor([[2., 7., 4.],
        [0., 4., 0.],
        [6., 7., 2.],
        [2., 3., 9.]])

# Seed has to be in the same cell

In [65]:
torch.manual_seed(1429)

torch.randint_like(a , low = 0, high = 10)

tensor([[7., 8., 0.],
        [9., 8., 3.],
        [6., 1., 6.],
        [1., 6., 1.]])

In [66]:
torch.randint_like(a , low = 0, high = 10)

tensor([[4., 7., 1.],
        [6., 9., 0.],
        [3., 4., 7.],
        [0., 0., 9.]])

# PyTorch Operations

In [68]:
x = torch.arange(10).reshape(5,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [71]:
x[1]

tensor([2, 3])

In [73]:
x[1,1]

tensor(3)

In [74]:
x[:,1]

tensor([1, 3, 5, 7, 9])

In [76]:
x[:,1:] # retain col like shape

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

# view and reshape are similar 

In [78]:
z = x.view(2,5) # not an inplace op but z is not liked to x
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [79]:
z[1] = 999
z

tensor([[  0,   1,   2,   3,   4],
        [999, 999, 999, 999, 999]])

In [80]:
x

tensor([[  0,   1],
        [  2,   3],
        [  4, 999],
        [999, 999],
        [999, 999]])

In [81]:
x.view(2,-1) # infer the cols when -1

tensor([[  0,   1,   2,   3,   4],
        [999, 999, 999, 999, 999]])

In [89]:
a = torch.randint(0,10, size = (1,9))

In [91]:
b = torch.randint(0,10, size = (1,9))

In [92]:
torch.add(a,b)

tensor([[ 4,  7,  4,  6,  7,  8, 11,  7,  4]])

In [94]:
a = a.add_(b) # _ is a inplace ops
a 

tensor([[ 6,  7,  7,  8, 14, 11, 18,  9,  8]])

# torch.dot() only accepts 1D ags while np.dot() accepts 2d

In [95]:
a = torch.randn((2,3))
a

tensor([[ 0.4727,  0.1247,  1.5947],
        [-2.4327, -1.0339, -1.6626]])

In [96]:
b = torch.randn((3,2))
b

tensor([[ 1.5222,  0.0575],
        [-0.6000, -0.3284],
        [ 0.5916, -0.3941]])

In [98]:
torch.dot(a,b) # we can use .mm for matrix mul

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [99]:
torch.mm(a,b)

tensor([[ 1.5882, -0.6423],
        [-4.0664,  0.8550]])

In [100]:
a @ b # normal 2d mat mul

tensor([[ 1.5882, -0.6423],
        [-4.0664,  0.8550]])

# Eucledian Norm

In [101]:
a 

tensor([[ 0.4727,  0.1247,  1.5947],
        [-2.4327, -1.0339, -1.6626]])

In [102]:
a.norm()

tensor(3.5402)

In [104]:
a.numel() # no of elements

6

In [105]:
len(a)

2

In [106]:
torch.cuda.is_available()

True

# Practice time

In [109]:
import numpy as np

In [110]:
from random import seed

In [111]:
seed(a = 42)

In [122]:
arr = np.random.randint(0,6, size = (1,6))

In [123]:
arr

array([[1, 5, 4, 2, 3, 5]])

In [124]:
tens = torch.tensor(arr)
tens

tensor([[1, 5, 4, 2, 3, 5]], dtype=torch.int32)

In [126]:
tens = tens.type(torch.int64)
tens

tensor([[1, 5, 4, 2, 3, 5]])

In [128]:
tens = tens.view(3,2)
tens

tensor([[1, 5],
        [4, 2],
        [3, 5]])

In [129]:
tens[:,1:]

tensor([[5],
        [2],
        [5]])

In [130]:
tens.square()

tensor([[ 1, 25],
        [16,  4],
        [ 9, 25]])

In [132]:
y = torch.rand_like(x.type(torch.float32))
y

tensor([[0.5257, 0.5340],
        [0.6499, 0.0160],
        [0.3833, 0.2664],
        [0.9259, 0.6311],
        [0.1983, 0.1711]])

In [135]:
y = y.view(2,5)

tensor([[  0,   1],
        [  2,   3],
        [  4, 999],
        [999, 999],
        [999, 999]])

In [138]:
torch.mm(x.type(torch.float32),y)

tensor([[2.6641e-01, 9.2590e-01, 6.3114e-01, 1.9832e-01, 1.7109e-01],
        [1.8506e+00, 3.8457e+00, 3.1932e+00, 6.2702e-01, 1.2798e+00],
        [2.6824e+02, 9.2711e+02, 6.3311e+02, 1.9818e+02, 1.7245e+02],
        [7.9130e+02, 1.4585e+03, 1.2798e+03, 2.1414e+02, 5.5382e+02],
        [7.9130e+02, 1.4585e+03, 1.2798e+03, 2.1414e+02, 5.5382e+02]])

In [140]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double)) 
else:
    print("NO GPU Available")

tensor([[   1,    2],
        [   3,    4],
        [   5, 1000],
        [1000, 1000],
        [1000, 1000]], device='cuda:0')
tensor([[   1.,    2.],
        [   3.,    4.],
        [   5., 1000.],
        [1000., 1000.],
        [1000., 1000.]], dtype=torch.float64)
